name: "camply"

include:
  - backend/docker-compose.yaml
  - frontend/docker-compose.yaml

services:
  backend:
    volumes:
      - ./.data/camply/:/home/camply/.local/share/camply/

  celery-worker:
    volumes:
      - ./.data/camply/:/home/camply/.local/share/camply/

  celery-beat:
    volumes:
      - ./.data/camply/:/home/camply/.local/share/camply/
